# Generated by Django 4.0.1 on 2022-11-10 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBank',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WalletBitcoin',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=7, max_digits=11)),
            ],
        ),
    ]
