# Generated by Django 4.0.1 on 2022-11-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbank',
            name='isconnected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletbitcoin',
            name='isconnected',
            field=models.BooleanField(default=False),
        ),
    ]
