# Generated by Django 4.0.1 on 2022-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbank',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
