# Generated by Django 4.0.1 on 2022-11-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinances', '0002_walletbank_isconnected_walletbitcoin_isconnected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletbank',
            name='isconnected',
        ),
        migrations.RemoveField(
            model_name='walletbitcoin',
            name='isconnected',
        ),
    ]
