# Generated by Django 4.0.1 on 2022-11-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinances', '0003_remove_walletbitcoin_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbitcoin',
            name='balance',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='walletbank',
            name='balance',
            field=models.FloatField(default=10000),
        ),
    ]
