# Generated by Django 4.0.1 on 2022-11-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinances', '0003_remove_walletbank_isconnected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbitcoin',
            name='balance',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
    ]
