# Generated by Django 4.0.1 on 2022-11-20 02:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinances', '0004_walletbitcoin_balance_alter_walletbank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbank',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='walletbitcoin',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
