# Generated by Django 4.0.1 on 2022-11-20 02:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinances', '0005_alter_walletbank_balance_alter_walletbitcoin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbitcoin',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.00000001'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))]),
        ),
    ]
