# Generated by Django 4.0.1 on 2022-11-10 00:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True)),
                ('gamepass', models.CharField(default='', max_length=10)),
                ('gameip', models.CharField(default='98.116.97.20', max_length=20, unique=True)),
                ('premium', models.BooleanField(default=False)),
                ('stats_game', models.BooleanField(default=False)),
                ('net', models.IntegerField(default=1)),
                ('money', models.IntegerField(default=10000)),
                ('isnpc', models.BooleanField(default=False)),
                ('ipconnected', models.CharField(default='off', max_length=20)),
                ('log', models.TextField(default='operating system created at 2022-11-10 00:47:26.885600')),
                ('istrail', models.BooleanField(default=False)),
                ('wallet_connect', models.CharField(default='off', max_length=100)),
                ('account_bank_connect', models.CharField(default='off', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeSofts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enigma',
            fields=[
                ('ip_trail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.CharField(default='', max_length=30000)),
                ('resposta', models.CharField(default='', max_length=30000)),
                ('current_ip', models.CharField(default='', max_length=30000)),
                ('next_ip', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LastIp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ip', models.CharField(default='0.0.0.0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softname', models.CharField(max_length=25)),
                ('softversion', models.IntegerField()),
                ('softsize', models.IntegerField()),
                ('softram', models.IntegerField()),
                ('softhidden', models.BooleanField(default=0)),
                ('softhiddenwith', models.BigIntegerField(default=0)),
                ('isactive', models.BooleanField(default=False)),
                ('softtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.typesofts')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipvictim', models.CharField(default='', max_length=20)),
                ('action', models.IntegerField()),
                ('timestart', models.DateTimeField()),
                ('timeend', models.DateTimeField()),
                ('logedit', models.TextField(default='')),
                ('iptryhack', models.CharField(default='', max_length=20)),
                ('softdownload', models.IntegerField(default=0)),
                ('softupload', models.IntegerField(default=0)),
                ('softdel', models.IntegerField(default=0)),
                ('softrun', models.IntegerField(default=0)),
                ('softstop', models.IntegerField(default=0)),
                ('uploadip', models.CharField(default='', max_length=20)),
                ('delmysoft', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('ismyserver', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('serverid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='SERVER', max_length=15)),
                ('cpu', models.FloatField(default=500)),
                ('hdd', models.FloatField(default=100)),
                ('ram', models.FloatField(default=256)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HackedDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphacked', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='enigma_solved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enigma_ip', models.CharField(default='', max_length=30000)),
                ('solved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
