# Generated by Django 4.0.1 on 2022-01-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(default='operating system created at 2022-01-09 18:33:39.952693+00:00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='37.132.74.182', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamepass',
            field=models.CharField(default='V4c63Hfb', max_length=10),
        ),
    ]
