# Generated by Django 4.0.1 on 2022-11-10 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistUsersCurrent',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reputation', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='63.23.248.193', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-10 01:13:48.016297'),
        ),
    ]
