# Generated by Django 4.0.1 on 2022-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_log_text_alter_user_gameip_alter_user_gamepass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(default='operating system created at 2022-01-09 18:57:29.237434+00:00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='221.231.196.99', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamepass',
            field=models.CharField(default='b8fCSExI', max_length=10),
        ),
    ]
