# Generated by Django 4.0.1 on 2022-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='softupload',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lastip',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='174.228.177.229', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-10-26 15:25:04.499662'),
        ),
    ]
