# Generated by Django 4.0.1 on 2022-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='cpu',
            field=models.IntegerField(default=512),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hdd',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='ram',
            field=models.IntegerField(default=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='191.137.148.77', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-18 23:32:42.347600'),
        ),
    ]
