# Generated by Django 4.0.1 on 2022-01-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_user_ipconected_alter_log_text_alter_user_gameip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ipconected',
            new_name='ipconnected',
        ),
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(default='operating system created at 2022-01-12 02:33:36.030334'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='254.100.95.180', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamepass',
            field=models.CharField(default='vIwx3lsF', max_length=10),
        ),
    ]
