# Generated by Django 4.0.1 on 2022-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_rename_ipconected_user_ipconnected_alter_log_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='iptryhack',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(default='operating system created at 2022-01-12 14:06:29.856432'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='199.134.128.185', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamepass',
            field=models.CharField(default='KhcYmccG', max_length=10),
        ),
    ]
