# Generated by Django 4.0.1 on 2022-10-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='istrail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='12.45.120.62', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-10-27 18:12:44.658743'),
        ),
    ]
