# Generated by Django 4.0.1 on 2022-01-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_processes_iptryhack_alter_log_text_alter_user_gameip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-01-13 17:12:24.193614'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='21.19.97.123', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamepass',
            field=models.CharField(default='emoUypHf', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='ipconnected',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
