# Generated by Django 4.0.1 on 2022-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_user_istrail_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='26.97.207.222', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-10-27 18:21:48.700713'),
        ),
    ]
