# Generated by Django 4.0.1 on 2022-10-27 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enigma',
            fields=[
                ('ip_trail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.CharField(default='', max_length=30000)),
                ('resposta', models.CharField(default='', max_length=30000)),
                ('next_ip', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='8.193.246.235', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-10-27 18:59:35.064044'),
        ),
    ]
