# Generated by Django 4.0.1 on 2022-01-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_user_log_alter_user_gameip_alter_user_gamepass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='softdownload',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='115.151.175.85', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamepass',
            field=models.CharField(default='lD3wPUui', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-01-17 16:19:28.835142'),
        ),
    ]
