# Generated by Django 4.0.1 on 2022-01-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_alter_user_gameip_alter_user_gamepass_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackeddatabase',
            name='iphacked',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='software',
            name='softhidden',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='204.196.131.252', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamepass',
            field=models.CharField(default='E0Yx5Idd', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-01-17 21:59:04.599196'),
        ),
    ]
