# Generated by Django 4.0.1 on 2022-10-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_enigma_current_ip_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigma',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='152.203.33.137', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-10-28 01:08:02.387778'),
        ),
    ]
