# Generated by Django 4.0.1 on 2022-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_alter_user_gameip_alter_user_log_enigma_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enigma',
            name='solved',
        ),
        migrations.AddField(
            model_name='enigma_solved',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='97.165.185.170', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-10-28 17:55:11.993222'),
        ),
    ]
