# Generated by Django 4.0.1 on 2022-10-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0017_remove_enigma_solved_enigma_solved_solved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enigma_solved',
            name='enigma',
        ),
        migrations.AddField(
            model_name='enigma_solved',
            name='enigma_ip',
            field=models.CharField(default='', max_length=30000),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='15.167.111.79', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-10-28 18:17:39.475419'),
        ),
    ]
