# Generated by Django 4.0.1 on 2022-11-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0021_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='91.194.6.11', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-03 15:38:10.103007'),
        ),
    ]
