# Generated by Django 4.0.1 on 2022-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0023_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processes',
            name='iptryhack',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='71.18.170.204', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-05 01:18:04.490270'),
        ),
    ]
