# Generated by Django 4.0.1 on 2022-11-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0027_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='71.162.204.40', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-05 03:00:55.693957'),
        ),
    ]
