# Generated by Django 4.0.1 on 2022-11-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0028_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='softdel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='247.117.205.22', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-06 01:42:59.118762'),
        ),
    ]
