# Generated by Django 4.0.1 on 2022-11-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0031_processes_ipvictim_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='softrun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='167.231.21.115', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-06 02:11:34.133667'),
        ),
    ]
