# Generated by Django 4.0.1 on 2022-11-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0035_alter_user_gameip_alter_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_bank_connect',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_connect',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='86.16.233.217', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-06 18:48:38.059904'),
        ),
    ]
