# Generated by Django 4.0.1 on 2022-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0036_user_account_bank_connect_user_wallet_connect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_bank_connect',
            field=models.CharField(default='off', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='79.249.189.145', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-06 18:54:32.900019'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_connect',
            field=models.CharField(default='off', max_length=100),
        ),
    ]
