# Generated by Django 4.0.1 on 2022-11-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0037_alter_user_account_bank_connect_alter_user_gameip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='77.117.17.31', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-06 18:58:24.630640'),
        ),
    ]
