# Generated by Django 4.0.1 on 2022-11-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0039_remove_user_wallet_connect_alter_user_gameip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_bank_connect',
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='95.197.172.162', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-06 20:29:07.766177'),
        ),
    ]
