# Generated by Django 4.0.1 on 2022-11-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0040_remove_user_account_bank_connect_alter_user_gameip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_bank_connect',
            field=models.CharField(default='off', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_connect',
            field=models.CharField(default='off', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='223.182.50.173', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-06 20:29:18.790588'),
        ),
    ]
