# Generated by Django 4.0.1 on 2022-11-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0041_user_account_bank_connect_user_wallet_connect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gameip',
            field=models.CharField(default='200.107.218.61', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.TextField(default='operating system created at 2022-11-07 12:51:38.533410'),
        ),
    ]
